### ISSUE TITLE
Is it possible to set connection for migration in config?

### ISSUE THREAD

**Issue by pyatnitsev** [doctrine/DoctrineMigrationsBundle#263] opened 2019-04-09 13:57 UTC
Hello!

I looking for way to set Doctrine connection for Migrations in yaml file. Is it possible? 

I use dedicated connection to execute all migrations and add ``--db`` option for each migration-related command is not beautiful. If I can't pass it by config, can I suggest a PR for that? Is it needed anybody else ?

**Comment by jwage** [comment] 2019-04-09 14:01
There are ways to do it but it is a more custom setup. See: https://www.doctrine-project.org/projects/doctrine-migrations/en/2.0/reference/configuration.html#advanced

DoctrineMigrationsBundle could probably be enhanced to make it a more simple configuration.

**Comment by pyatnitsev** [comment] 2019-04-09 14:11
I can add `connection` option to configuration of the bundle, that accept string of existed doctrine connection. Ok?

**Comment by pyatnitsev** [comment] 2019-05-08 15:50
this is clone of #189

**Comment by alcaeus** [comment] 2019-05-08 17:34
Closing as duplicate of #189.

**Closed by alcaeus** 2019-05-08 17:34 UTC
