### ISSUE TITLE
Php 8

### ISSUE THREAD

**Issue by ghost** [doctrine/DoctrineMigrationsBundle#388] opened 2020-12-14 20:45 UTC
Hi 

I want to create a PR for support php 8 I can ?

**Comment by luchaninov** [comment] 2020-12-15 15:50
duplicate of https://github.com/doctrine/DoctrineMigrationsBundle/issues/362 ?

**Comment by stof** [comment] 2020-12-15 17:54
I'm closing this as duplicate.

Btw, even the PR already exists at https://github.com/doctrine/DoctrineMigrationsBundle/pull/383 (but it depends on the work being done in the library first)

**Closed as completed by stof** 2020-12-15 17:54 UTC
