### ISSUE TITLE
There is no active transaction

### ISSUE THREAD

**Issue by brian978** [doctrine/DoctrineMigrationsBundle#395] opened 2021-01-11 08:31 UTC
I updated today to Doctrine Migrations v3.0 and after I updated all the configrations in Symfony I keep receiving and error that there is no active transaction.

Any thoughts on how to solve this?

Please note that the only thing that I changed in the migration files was the namespace in order to comply with the new structure from Symfony

Logs:
```[2021-01-11T07:56:45.438521+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-01-11T07:56:45.481731+00:00] doctrine.DEBUG: CREATE TABLE doctrine_migration_versions (version VARCHAR(191) NOT NULL, executed_at DATETIME DEFAULT NULL, execution_time INT DEFAULT NULL, PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB [] []
[2021-01-11T07:56:45.679316+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-01-11T07:56:45.680325+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-01-11T07:56:45.683116+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'my_table' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-01-11T07:56:45.685056+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'my_table' /*!50116 AND c.constraint_schema = 'my_table' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-01-11T07:56:45.686147+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'my_table' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-01-11T07:56:45.686867+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-01-11T07:56:45.688956+00:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-01-11T07:56:45.690807+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-01-11T07:56:45.691518+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-01-11T07:56:45.692256+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'my_table' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-01-11T07:56:45.693206+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'my_table' /*!50116 AND c.constraint_schema = 'my_table' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-01-11T07:56:45.693857+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'my_table' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-01-11T07:56:45.694591+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-01-11T07:56:45.695340+00:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-01-11T07:56:45.696099+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-01-11T07:56:45.696836+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-01-11T07:56:45.697604+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'my_table' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-01-11T07:56:45.699318+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'my_table' /*!50116 AND c.constraint_schema = 'my_table' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-01-11T07:56:45.700140+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'my_table' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-01-11T07:56:45.700946+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-01-11T07:56:45.701616+00:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-01-11T07:56:45.728618+00:00] doctrine.DEBUG: "START TRANSACTION" [] []
<my create & alter table statement from the migration files>
[2021-01-11T07:56:54.886393+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-01-11T07:56:54.888439+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'my_table' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-01-11T07:56:54.890574+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'my_table' /*!50116 AND c.constraint_schema = 'my_table' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-01-11T07:56:54.892229+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'my_table' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-01-11T07:56:54.893559+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-01-11T07:56:54.894464+00:00] doctrine.DEBUG: INSERT INTO doctrine_migration_versions (version, executed_at, execution_te) VALUES (?, ?, ?) ["DoctrineMigrations\\Version [...]","2021-01-11T07:56:45+00:00",9154] []
[2021-01-11T07:56:54.935814+00:00] doctrine.DEBUG: "COMMIT" [] []
[2021-01-11T07:56:54.939584+00:00] doctrine.DEBUG: "ROLLBACK" [] []
[2021-01-11T07:56:54.950907+00:00] console.ERROR: Error thrown while running command "doctrine:migrations:migrate". Message: "There is no active transaction" {"exception":"[object] (PDOException(code: 0): There is no active transaction at /var/www/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1761)","command":"doctrine:migrations:migrate","message":"There is no active transaction"} []
[2021-01-11T07:56:54.952148+00:00] console.DEBUG: Command "doctrine:migrations:migrate" exited with code "1" {"command":"doctrine:migrations:migrate","code":1} []
```

**Comment by ntavelis** [comment] 2021-01-13 09:15
Same issue here, fresh symfony installation (5.2.1) and php 8

**Comment by stof** [comment] 2021-01-13 10:28
Closing as duplicate of https://github.com/doctrine/migrations/issues/1104 which is the right place to discuss it

**Closed as completed by stof** 2021-01-13 10:28 UTC
