### ISSUE TITLE
Unable to use preconfigured migrations table name

### ISSUE THREAD

**Issue by aar0nr** [doctrine/DoctrineMigrationsBundle#173] opened 2016-06-02 21:12 UTC
This line is causing me problems:

https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/Command/DoctrineCommand.php#L62

In my application, the `Doctrine\DBAL\Migrations\Configuration\Configuration` object is already configured and set on the doctrine migration commands. However, this conditional uses a `||` operator instead of a `&&` operator, and even though the configuration object has a table name already configured, it still reads it from the container.

**Comment by goetas** [comment] 2020-04-25 15:53
Closing this as the issue is not clear what is the propose for this change,  the pull request got closed, the issue is almost 4 years old, and the 1.x branch is abandoned.

**Closed by goetas** 2020-04-25 15:53 UTC
