### ISSUE TITLE
"There is no active transaction" error after successfully performing migrations

### ISSUE THREAD

**Issue by bartfeenstra** [doctrine/DoctrineMigrationsBundle#393] opened 2021-01-04 15:33 UTC
## Problem

When performing migrations, the process ends with "There is no active transaction" thrown in `Connection.php` on line 1761. The migrations themselves are performed successfully: the database schema appears to be altered as expected, and when re-running migrations Doctrine is aware that all migrations have been run successfully previously already.

The problem occurred for the first time after the migration from PHP 7.4 to 8.0.0.

The problem occurs when performing migrations through the `doctrine:migrations:migrate` command, as well as when performed in code by [dama/doctrine-test-bundle](https://packagist.org/packages/dama/doctrine-test-bundle).

### Update 2021-01-05
This may be a pdo_mysql issue. See https://twitter.com/derrabus/status/1346405883429924870

## Package versions
- doctrine/migrations 3.0.2
- doctrine/doctrine-migrations-bundle 3.0.2
- doctrine/dbal 2.12.1

## Related issues
- https://twitter.com/derrabus/status/1346405883429924870
- https://github.com/doctrine/dbal/pull/4452 has the same error under similar circumstances, but proposed the wrong fix.

**Comment by dlgoodchild** [comment] 2021-01-07 10:25
I've just experienced this now myself on PHP v8.0.0.
I changed no composer dependencies and simply rolled the container back to 7.4.10 and the migrations worked.

![-zsh](https://user-images.githubusercontent.com/366030/103881667-0cef4780-50db-11eb-9e80-4bfc8cd0ceb5.png)

Executing migrations on PHP 8 currently does not work, however I believe it likely relates to `doctrine/migrations` as that's what's common between myself @bartfeenstra 

## Package versions
- doctrine/orm 2.8.1
- doctrine/migrations 3.0.2

**Comment by lukasluecke** [comment] 2021-01-07 11:06
A temporary workaround would be to override `isTransactional()` to return `false` - if not having a transaction is acceptable for your migrations.

**Comment by greg0ire** [comment] 2021-01-07 14:53
Duplicate of https://github.com/doctrine/migrations/issues/1104

**Closed as completed by greg0ire** 2021-01-07 14:53 UTC

**Comment by yyaremenko** [comment] 2021-06-02 14:48
**IF YOU STILL GET THIS ERROR**

**if you use Doctrine Migrations Bundle**
make sure to update the bundle to ^3.1.1 version (but first update the doctrine migrations library);
for both of these, run this single command
```
composer update doctrine/migrations && composer require doctrine/doctrine-migrations-bundle:^3.1.1
```

**if you use Doctrine Migrations directly, without bundle**, as prompted by @azjezz
> If you are using doctrine migrations 2, run the following:
> 
> ```
> composer require doctrine/migrations:^2.3.3
> ```
> 
> If you are using doctrine migrations 3, run the following:
> 
> ```
> composer require doctrine/migrations:^3.1.1
> ```

**Comment by azjezz** [comment] 2021-06-02 14:49
@yyaremenko the proposed solution works even if you are using the bundle, the bug is in the doctrine/migrations lib, not the bundle :)

**Comment by yyaremenko** [comment] 2021-06-02 14:58
@azjezz yes, I agree and I understand, but the idea with the bundle is that you don't require the library directly in your composer.json; if I use your solution while using bundle, I get the following in my composer.json
```
...
        "doctrine/doctrine-migrations-bundle": "^3.0",
        "doctrine/migrations": "^3.1.1",
...
```
The things may get messy quite fast.

**Comment by garak** [comment] 2021-06-15 08:17
I started to get this error too (since I migrated to PHP 8), but I don't use doctrine migrations.
I just execute:
```php
<?php
/** @var \Doctrine\DBAL\Connection $connection */
$connection->beginTransaction();
$connection->executeStatement('SET FOREIGN_KEY_CHECKS=0;');
$connection->executeStatement($sql);
$connection->executeStatement('SET FOREIGN_KEY_CHECKS=1;');
$connection->commit();
```
Is there a place in Doctrine where I can look for?

**Comment by greg0ire** [comment] 2021-06-15 08:35
I think you might be able to reproduce it in pure PDO too. If that's true, you will understand that there is not much we can do.

**Comment by garak** [comment] 2021-06-15 08:37
> I think you might be able to reproduce it in pure PDO too. If that's true, you will understand that there is not much we can do.

I see. Is there any issue elsewhere I can follow?

**Comment by greg0ire** [comment] 2021-06-15 08:44
I don't think there is anything to follow, because there is nothing we should do IMO. You can get an in-depth explanation about implicit commits here though: https://github.com/doctrine/migrations/pull/1157/files

**Comment by garak** [comment] 2021-06-15 08:56
Thank @greg0ire. I solved by splitting my sql (one with table deletion/creation and one with everything else)

**Comment by ingfdoaguirre** [comment] 2022-02-12 23:36
Hi, maybe is not the correct solution or the one that everyone wants, but you can use PDO directly with DDL and run exec().

```
use PDO;
use PDOException;

try{
    $dsn = 'mysql:host=testhost;dbname=testname;charset=testchartset';
    $pdo = new PDO($dsn, 'testuser' , 'testpass');
    $sql = 'CREATE TABLE ..............';
    $pdo->exec($sql);
} catch (PDOException $e){
    return $e->getMessage();
}
```

And there will be no "There is no active transaction" error code.

You can outwit me or be upset and say "this is an antipattern", but it works.

**Comment by ingfdoaguirre** [comment] 2022-02-13 00:02
> I started to get this error too (since I migrated to PHP 8), but I don't use doctrine migrations. I just execute:
> 
> ```
> <?php
> /** @var \Doctrine\DBAL\Connection $connection */
> $connection->beginTransaction();
> $connection->executeStatement('SET FOREIGN_KEY_CHECKS=0;');
> $connection->executeStatement($sql);
> $connection->executeStatement('SET FOREIGN_KEY_CHECKS=1;');
> $connection->commit();
> ```
> 
> Is there a place in Doctrine where I can look for?

Hi, maybe is not the correct solution or the one that everyone wants, but you can use PDO directly with DDL and run exec() (AS A TEMPORARY SOLUTION).

```
use PDO;
use PDOException;

try{
    $dsn = 'mysql:host=testhost;dbname=testname;charset=testchartset';
    $pdo = new PDO($dsn, 'testuser' , 'testpass');
    $sql = 'CREATE TABLE ..............';
    $pdo->exec($sql);
} catch (PDOException $e){
    return $e->getMessage();
}
```

And there will be no "There is no active transaction" error code. I'm using php 8.1 and Symfony 6.0.3

You can outwit me or be upset and say "this is an antipattern", but it works.

**Comment by greg0ire** [comment] 2022-02-13 07:32
Well it does work if you have one statement, but as soon as you have 2 of them, is no longer does. As for the outwitting, if you use MySQL or Oracle, that means you cannot use DDL in a transaction, so… maybe, you know, just don't?

**Comment by Nek-** [comment] 2023-08-31 15:36
@greg0ire would a PR adding the option `transactional` in the bundle config be accepted?

(Mb, I saw it's already done, just not compatible with dbal 2.x 🙈 )

**Comment by Tofandel** [comment] 2025-04-11 00:21
I am still hitting this issue with the latest versions of everything

I set my migrations to non transactional but if the database is blank (which is a normal state for running tests) at some point when I use the cache during a transaction it creates the `cache_items` table and then this issue happens

What bothers me is, this table is not supposed to be created during a transaction and indeed `$this->conn->isTransactionActive()` is `false`
```php
if (!$this->conn->isTransactionActive() || \in_array($platformName, ['pgsql', 'sqlite', 'sqlsrv'], true)) {
    $this->createTable();
}
```

This is problematic because test units fail on warning
